### ISSUE TITLE
Failed connect to s3.amazonaws.com:443; No error

### ISSUE THREAD

**Issue by Huangdong2** [kraksoft/vagrant-box-debian#1]
hi kraksoft:
![s3](https://cloud.githubusercontent.com/assets/9297437/7445952/f65cf288-f1f9-11e4-9a93-4d27975b6a17.png)

i'm from china, plz help with vagrant as  the following
downloading error:
github-debian-7.8.0-amd64.box

**Comment by kedrap** [comment]
Can't reproduce
